
spring:

# redis
#  cache:
#    type: redis
#  redis:
#    host: 127.0.0.1
#    port: 6379
#    username:
#    password:

  # Thymleaf
  thymeleaf:
    prefix: classpath:/templates/

#파일 저장
  servlet:
    multipart:
      enabled: true
      max-request-size: 100MB
      max-file-size: 100MB

#  h2:
#    console:
#      enabled: true
#      path: /h2-console

  datasource:
    url: jdbc:mysql://localhost:3306/comedb
#    url: jdbc:mysql://sns.cyslqz4yprk6.ap-northeast-2.rds.amazonaws.com:3306/sns
#    username: admin
#    password : po6568tygh!
    username: root
    password: 6568
    driver-class-name: com.mysql.cj.jdbc.Driver


  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: false
    defer-datasource-initialization: true
    profiles:
      active: true
    database: mysql
#
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

file:
  dir: /Users/seungsu/dev/sns/src/main/resources/static/img/

# weather api key
weatherKey: cuNe1YMC4Qsginx6w4aexI6qIHu%2FbHYZPa34K58T3ipMCCHCmKuigo9imZv7FqYFOL0Lkit8QRlJH9T4Yd5bvQ%3D%3D
