spring:
  servlet:
    multipart:
      enabled: true
      max-request-size: 100MB
      max-file-size: 100MB


#  h2:
#    console:
#      enabled: true
#      path: /h2-console

  datasource:
    url: jdbc:mysql://localhost:3306/comedb
    username: root
    password: 6568
    driver-class-name: com.mysql.cj.jdbc.Driver


  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: false
    defer-datasource-initialization: true
    profiles:
      active: true
    database: mysql

file:
  dir: /Users/seungsu/dev/sns/src/main/resources/static/img/

