spring:
  servlet:
    multipart:
      enabled: true
      max-request-size: 100MB
      max-file-size: 100MB


  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:sns
    username: ss
    password:


  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hiberante:
        format_sql : true
    database-platform: org.hibernate.dialect.H2Dialect

